[build]
    command = "npm run build && npm run generate:pages"
    functions="functions"
    publish = "dist"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status=200

[[redirects]]
    from = "/generated/*"
    to = "/generated/:splat"
    status=200
